domain: psyntium.github.io
url: https://psyntium.github.io
baseurl: /kirajap
version: 0.5
description: KiraJap application for children aged 7 to 9 is designed to help children improve their mathematical skills in a fun and engaging way. It includes exercises on fundamental mathematical concepts such as addition, subtraction, multiplication, and division, with customizable difficulty levels to suit the child's abilities. The app has an easy-to-use interface with clear instructions and feedback to help children understand their progress. Overall, KiraJap application is an effective tool for improving children's mathematical skills and knowledge.
keywords: Math, Mathematics, KiraJap, Matematik, Addition, Tambah, Subtraction, Tolak, Multiplication, Darab, Division, Bahagi
author: Aiman Shaharuddin